package com.zhy.people.beans;

import com.zhy.common.page.Page;
import java.util.ArrayList;
import java.util.List;

public class CommonTaskExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_COMMON_TASK
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_COMMON_TASK
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_COMMON_TASK
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_COMMON_TASK
     *
     * @mbg.generated
     */
    protected Page page;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_COMMON_TASK
     *
     * @mbg.generated
     */
    public CommonTaskExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_COMMON_TASK
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_COMMON_TASK
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_COMMON_TASK
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_COMMON_TASK
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_COMMON_TASK
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_COMMON_TASK
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_COMMON_TASK
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_COMMON_TASK
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_COMMON_TASK
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_COMMON_TASK
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_COMMON_TASK
     *
     * @mbg.generated
     */
    public void setPage(Page page) {
        this.page=page;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_COMMON_TASK
     *
     * @mbg.generated
     */
    public Page getPage() {
        return page;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_COMMON_TASK
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andFLOWIDIsNull() {
            addCriterion("FLOWID is null");
            return (Criteria) this;
        }

        public Criteria andFLOWIDIsNotNull() {
            addCriterion("FLOWID is not null");
            return (Criteria) this;
        }

        public Criteria andFLOWIDEqualTo(String value) {
            addCriterion("FLOWID =", value, "FLOWID");
            return (Criteria) this;
        }

        public Criteria andFLOWIDNotEqualTo(String value) {
            addCriterion("FLOWID <>", value, "FLOWID");
            return (Criteria) this;
        }

        public Criteria andFLOWIDGreaterThan(String value) {
            addCriterion("FLOWID >", value, "FLOWID");
            return (Criteria) this;
        }

        public Criteria andFLOWIDGreaterThanOrEqualTo(String value) {
            addCriterion("FLOWID >=", value, "FLOWID");
            return (Criteria) this;
        }

        public Criteria andFLOWIDLessThan(String value) {
            addCriterion("FLOWID <", value, "FLOWID");
            return (Criteria) this;
        }

        public Criteria andFLOWIDLessThanOrEqualTo(String value) {
            addCriterion("FLOWID <=", value, "FLOWID");
            return (Criteria) this;
        }

        public Criteria andFLOWIDLike(String value) {
            addCriterion("FLOWID like", value, "FLOWID");
            return (Criteria) this;
        }

        public Criteria andFLOWIDNotLike(String value) {
            addCriterion("FLOWID not like", value, "FLOWID");
            return (Criteria) this;
        }

        public Criteria andFLOWIDIn(List<String> values) {
            addCriterion("FLOWID in", values, "FLOWID");
            return (Criteria) this;
        }

        public Criteria andFLOWIDNotIn(List<String> values) {
            addCriterion("FLOWID not in", values, "FLOWID");
            return (Criteria) this;
        }

        public Criteria andFLOWIDBetween(String value1, String value2) {
            addCriterion("FLOWID between", value1, value2, "FLOWID");
            return (Criteria) this;
        }

        public Criteria andFLOWIDNotBetween(String value1, String value2) {
            addCriterion("FLOWID not between", value1, value2, "FLOWID");
            return (Criteria) this;
        }

        public Criteria andTASKIDIsNull() {
            addCriterion("TASKID is null");
            return (Criteria) this;
        }

        public Criteria andTASKIDIsNotNull() {
            addCriterion("TASKID is not null");
            return (Criteria) this;
        }

        public Criteria andTASKIDEqualTo(String value) {
            addCriterion("TASKID =", value, "TASKID");
            return (Criteria) this;
        }

        public Criteria andTASKIDNotEqualTo(String value) {
            addCriterion("TASKID <>", value, "TASKID");
            return (Criteria) this;
        }

        public Criteria andTASKIDGreaterThan(String value) {
            addCriterion("TASKID >", value, "TASKID");
            return (Criteria) this;
        }

        public Criteria andTASKIDGreaterThanOrEqualTo(String value) {
            addCriterion("TASKID >=", value, "TASKID");
            return (Criteria) this;
        }

        public Criteria andTASKIDLessThan(String value) {
            addCriterion("TASKID <", value, "TASKID");
            return (Criteria) this;
        }

        public Criteria andTASKIDLessThanOrEqualTo(String value) {
            addCriterion("TASKID <=", value, "TASKID");
            return (Criteria) this;
        }

        public Criteria andTASKIDLike(String value) {
            addCriterion("TASKID like", value, "TASKID");
            return (Criteria) this;
        }

        public Criteria andTASKIDNotLike(String value) {
            addCriterion("TASKID not like", value, "TASKID");
            return (Criteria) this;
        }

        public Criteria andTASKIDIn(List<String> values) {
            addCriterion("TASKID in", values, "TASKID");
            return (Criteria) this;
        }

        public Criteria andTASKIDNotIn(List<String> values) {
            addCriterion("TASKID not in", values, "TASKID");
            return (Criteria) this;
        }

        public Criteria andTASKIDBetween(String value1, String value2) {
            addCriterion("TASKID between", value1, value2, "TASKID");
            return (Criteria) this;
        }

        public Criteria andTASKIDNotBetween(String value1, String value2) {
            addCriterion("TASKID not between", value1, value2, "TASKID");
            return (Criteria) this;
        }

        public Criteria andPROCESSINSTANCEIDIsNull() {
            addCriterion("PROCESSINSTANCEID is null");
            return (Criteria) this;
        }

        public Criteria andPROCESSINSTANCEIDIsNotNull() {
            addCriterion("PROCESSINSTANCEID is not null");
            return (Criteria) this;
        }

        public Criteria andPROCESSINSTANCEIDEqualTo(String value) {
            addCriterion("PROCESSINSTANCEID =", value, "PROCESSINSTANCEID");
            return (Criteria) this;
        }

        public Criteria andPROCESSINSTANCEIDNotEqualTo(String value) {
            addCriterion("PROCESSINSTANCEID <>", value, "PROCESSINSTANCEID");
            return (Criteria) this;
        }

        public Criteria andPROCESSINSTANCEIDGreaterThan(String value) {
            addCriterion("PROCESSINSTANCEID >", value, "PROCESSINSTANCEID");
            return (Criteria) this;
        }

        public Criteria andPROCESSINSTANCEIDGreaterThanOrEqualTo(String value) {
            addCriterion("PROCESSINSTANCEID >=", value, "PROCESSINSTANCEID");
            return (Criteria) this;
        }

        public Criteria andPROCESSINSTANCEIDLessThan(String value) {
            addCriterion("PROCESSINSTANCEID <", value, "PROCESSINSTANCEID");
            return (Criteria) this;
        }

        public Criteria andPROCESSINSTANCEIDLessThanOrEqualTo(String value) {
            addCriterion("PROCESSINSTANCEID <=", value, "PROCESSINSTANCEID");
            return (Criteria) this;
        }

        public Criteria andPROCESSINSTANCEIDLike(String value) {
            addCriterion("PROCESSINSTANCEID like", value, "PROCESSINSTANCEID");
            return (Criteria) this;
        }

        public Criteria andPROCESSINSTANCEIDNotLike(String value) {
            addCriterion("PROCESSINSTANCEID not like", value, "PROCESSINSTANCEID");
            return (Criteria) this;
        }

        public Criteria andPROCESSINSTANCEIDIn(List<String> values) {
            addCriterion("PROCESSINSTANCEID in", values, "PROCESSINSTANCEID");
            return (Criteria) this;
        }

        public Criteria andPROCESSINSTANCEIDNotIn(List<String> values) {
            addCriterion("PROCESSINSTANCEID not in", values, "PROCESSINSTANCEID");
            return (Criteria) this;
        }

        public Criteria andPROCESSINSTANCEIDBetween(String value1, String value2) {
            addCriterion("PROCESSINSTANCEID between", value1, value2, "PROCESSINSTANCEID");
            return (Criteria) this;
        }

        public Criteria andPROCESSINSTANCEIDNotBetween(String value1, String value2) {
            addCriterion("PROCESSINSTANCEID not between", value1, value2, "PROCESSINSTANCEID");
            return (Criteria) this;
        }

        public Criteria andTYPEIDIsNull() {
            addCriterion("TYPEID is null");
            return (Criteria) this;
        }

        public Criteria andTYPEIDIsNotNull() {
            addCriterion("TYPEID is not null");
            return (Criteria) this;
        }

        public Criteria andTYPEIDEqualTo(String value) {
            addCriterion("TYPEID =", value, "TYPEID");
            return (Criteria) this;
        }

        public Criteria andTYPEIDNotEqualTo(String value) {
            addCriterion("TYPEID <>", value, "TYPEID");
            return (Criteria) this;
        }

        public Criteria andTYPEIDGreaterThan(String value) {
            addCriterion("TYPEID >", value, "TYPEID");
            return (Criteria) this;
        }

        public Criteria andTYPEIDGreaterThanOrEqualTo(String value) {
            addCriterion("TYPEID >=", value, "TYPEID");
            return (Criteria) this;
        }

        public Criteria andTYPEIDLessThan(String value) {
            addCriterion("TYPEID <", value, "TYPEID");
            return (Criteria) this;
        }

        public Criteria andTYPEIDLessThanOrEqualTo(String value) {
            addCriterion("TYPEID <=", value, "TYPEID");
            return (Criteria) this;
        }

        public Criteria andTYPEIDLike(String value) {
            addCriterion("TYPEID like", value, "TYPEID");
            return (Criteria) this;
        }

        public Criteria andTYPEIDNotLike(String value) {
            addCriterion("TYPEID not like", value, "TYPEID");
            return (Criteria) this;
        }

        public Criteria andTYPEIDIn(List<String> values) {
            addCriterion("TYPEID in", values, "TYPEID");
            return (Criteria) this;
        }

        public Criteria andTYPEIDNotIn(List<String> values) {
            addCriterion("TYPEID not in", values, "TYPEID");
            return (Criteria) this;
        }

        public Criteria andTYPEIDBetween(String value1, String value2) {
            addCriterion("TYPEID between", value1, value2, "TYPEID");
            return (Criteria) this;
        }

        public Criteria andTYPEIDNotBetween(String value1, String value2) {
            addCriterion("TYPEID not between", value1, value2, "TYPEID");
            return (Criteria) this;
        }

        public Criteria andFLOWNAMEIsNull() {
            addCriterion("FLOWNAME is null");
            return (Criteria) this;
        }

        public Criteria andFLOWNAMEIsNotNull() {
            addCriterion("FLOWNAME is not null");
            return (Criteria) this;
        }

        public Criteria andFLOWNAMEEqualTo(String value) {
            addCriterion("FLOWNAME =", value, "FLOWNAME");
            return (Criteria) this;
        }

        public Criteria andFLOWNAMENotEqualTo(String value) {
            addCriterion("FLOWNAME <>", value, "FLOWNAME");
            return (Criteria) this;
        }

        public Criteria andFLOWNAMEGreaterThan(String value) {
            addCriterion("FLOWNAME >", value, "FLOWNAME");
            return (Criteria) this;
        }

        public Criteria andFLOWNAMEGreaterThanOrEqualTo(String value) {
            addCriterion("FLOWNAME >=", value, "FLOWNAME");
            return (Criteria) this;
        }

        public Criteria andFLOWNAMELessThan(String value) {
            addCriterion("FLOWNAME <", value, "FLOWNAME");
            return (Criteria) this;
        }

        public Criteria andFLOWNAMELessThanOrEqualTo(String value) {
            addCriterion("FLOWNAME <=", value, "FLOWNAME");
            return (Criteria) this;
        }

        public Criteria andFLOWNAMELike(String value) {
            addCriterion("FLOWNAME like", value, "FLOWNAME");
            return (Criteria) this;
        }

        public Criteria andFLOWNAMENotLike(String value) {
            addCriterion("FLOWNAME not like", value, "FLOWNAME");
            return (Criteria) this;
        }

        public Criteria andFLOWNAMEIn(List<String> values) {
            addCriterion("FLOWNAME in", values, "FLOWNAME");
            return (Criteria) this;
        }

        public Criteria andFLOWNAMENotIn(List<String> values) {
            addCriterion("FLOWNAME not in", values, "FLOWNAME");
            return (Criteria) this;
        }

        public Criteria andFLOWNAMEBetween(String value1, String value2) {
            addCriterion("FLOWNAME between", value1, value2, "FLOWNAME");
            return (Criteria) this;
        }

        public Criteria andFLOWNAMENotBetween(String value1, String value2) {
            addCriterion("FLOWNAME not between", value1, value2, "FLOWNAME");
            return (Criteria) this;
        }

        public Criteria andPROPOSERIsNull() {
            addCriterion("PROPOSER is null");
            return (Criteria) this;
        }

        public Criteria andPROPOSERIsNotNull() {
            addCriterion("PROPOSER is not null");
            return (Criteria) this;
        }

        public Criteria andPROPOSEREqualTo(String value) {
            addCriterion("PROPOSER =", value, "PROPOSER");
            return (Criteria) this;
        }

        public Criteria andPROPOSERNotEqualTo(String value) {
            addCriterion("PROPOSER <>", value, "PROPOSER");
            return (Criteria) this;
        }

        public Criteria andPROPOSERGreaterThan(String value) {
            addCriterion("PROPOSER >", value, "PROPOSER");
            return (Criteria) this;
        }

        public Criteria andPROPOSERGreaterThanOrEqualTo(String value) {
            addCriterion("PROPOSER >=", value, "PROPOSER");
            return (Criteria) this;
        }

        public Criteria andPROPOSERLessThan(String value) {
            addCriterion("PROPOSER <", value, "PROPOSER");
            return (Criteria) this;
        }

        public Criteria andPROPOSERLessThanOrEqualTo(String value) {
            addCriterion("PROPOSER <=", value, "PROPOSER");
            return (Criteria) this;
        }

        public Criteria andPROPOSERLike(String value) {
            addCriterion("PROPOSER like", value, "PROPOSER");
            return (Criteria) this;
        }

        public Criteria andPROPOSERNotLike(String value) {
            addCriterion("PROPOSER not like", value, "PROPOSER");
            return (Criteria) this;
        }

        public Criteria andPROPOSERIn(List<String> values) {
            addCriterion("PROPOSER in", values, "PROPOSER");
            return (Criteria) this;
        }

        public Criteria andPROPOSERNotIn(List<String> values) {
            addCriterion("PROPOSER not in", values, "PROPOSER");
            return (Criteria) this;
        }

        public Criteria andPROPOSERBetween(String value1, String value2) {
            addCriterion("PROPOSER between", value1, value2, "PROPOSER");
            return (Criteria) this;
        }

        public Criteria andPROPOSERNotBetween(String value1, String value2) {
            addCriterion("PROPOSER not between", value1, value2, "PROPOSER");
            return (Criteria) this;
        }

        public Criteria andTASKNAMEIsNull() {
            addCriterion("TASKNAME is null");
            return (Criteria) this;
        }

        public Criteria andTASKNAMEIsNotNull() {
            addCriterion("TASKNAME is not null");
            return (Criteria) this;
        }

        public Criteria andTASKNAMEEqualTo(String value) {
            addCriterion("TASKNAME =", value, "TASKNAME");
            return (Criteria) this;
        }

        public Criteria andTASKNAMENotEqualTo(String value) {
            addCriterion("TASKNAME <>", value, "TASKNAME");
            return (Criteria) this;
        }

        public Criteria andTASKNAMEGreaterThan(String value) {
            addCriterion("TASKNAME >", value, "TASKNAME");
            return (Criteria) this;
        }

        public Criteria andTASKNAMEGreaterThanOrEqualTo(String value) {
            addCriterion("TASKNAME >=", value, "TASKNAME");
            return (Criteria) this;
        }

        public Criteria andTASKNAMELessThan(String value) {
            addCriterion("TASKNAME <", value, "TASKNAME");
            return (Criteria) this;
        }

        public Criteria andTASKNAMELessThanOrEqualTo(String value) {
            addCriterion("TASKNAME <=", value, "TASKNAME");
            return (Criteria) this;
        }

        public Criteria andTASKNAMELike(String value) {
            addCriterion("TASKNAME like", value, "TASKNAME");
            return (Criteria) this;
        }

        public Criteria andTASKNAMENotLike(String value) {
            addCriterion("TASKNAME not like", value, "TASKNAME");
            return (Criteria) this;
        }

        public Criteria andTASKNAMEIn(List<String> values) {
            addCriterion("TASKNAME in", values, "TASKNAME");
            return (Criteria) this;
        }

        public Criteria andTASKNAMENotIn(List<String> values) {
            addCriterion("TASKNAME not in", values, "TASKNAME");
            return (Criteria) this;
        }

        public Criteria andTASKNAMEBetween(String value1, String value2) {
            addCriterion("TASKNAME between", value1, value2, "TASKNAME");
            return (Criteria) this;
        }

        public Criteria andTASKNAMENotBetween(String value1, String value2) {
            addCriterion("TASKNAME not between", value1, value2, "TASKNAME");
            return (Criteria) this;
        }

        public Criteria andSTATEIsNull() {
            addCriterion("STATE is null");
            return (Criteria) this;
        }

        public Criteria andSTATEIsNotNull() {
            addCriterion("STATE is not null");
            return (Criteria) this;
        }

        public Criteria andSTATEEqualTo(String value) {
            addCriterion("STATE =", value, "STATE");
            return (Criteria) this;
        }

        public Criteria andSTATENotEqualTo(String value) {
            addCriterion("STATE <>", value, "STATE");
            return (Criteria) this;
        }

        public Criteria andSTATEGreaterThan(String value) {
            addCriterion("STATE >", value, "STATE");
            return (Criteria) this;
        }

        public Criteria andSTATEGreaterThanOrEqualTo(String value) {
            addCriterion("STATE >=", value, "STATE");
            return (Criteria) this;
        }

        public Criteria andSTATELessThan(String value) {
            addCriterion("STATE <", value, "STATE");
            return (Criteria) this;
        }

        public Criteria andSTATELessThanOrEqualTo(String value) {
            addCriterion("STATE <=", value, "STATE");
            return (Criteria) this;
        }

        public Criteria andSTATELike(String value) {
            addCriterion("STATE like", value, "STATE");
            return (Criteria) this;
        }

        public Criteria andSTATENotLike(String value) {
            addCriterion("STATE not like", value, "STATE");
            return (Criteria) this;
        }

        public Criteria andSTATEIn(List<String> values) {
            addCriterion("STATE in", values, "STATE");
            return (Criteria) this;
        }

        public Criteria andSTATENotIn(List<String> values) {
            addCriterion("STATE not in", values, "STATE");
            return (Criteria) this;
        }

        public Criteria andSTATEBetween(String value1, String value2) {
            addCriterion("STATE between", value1, value2, "STATE");
            return (Criteria) this;
        }

        public Criteria andSTATENotBetween(String value1, String value2) {
            addCriterion("STATE not between", value1, value2, "STATE");
            return (Criteria) this;
        }

        public Criteria andSUBMISSIONDATEIsNull() {
            addCriterion("SUBMISSIONDATE is null");
            return (Criteria) this;
        }

        public Criteria andSUBMISSIONDATEIsNotNull() {
            addCriterion("SUBMISSIONDATE is not null");
            return (Criteria) this;
        }

        public Criteria andSUBMISSIONDATEEqualTo(String value) {
            addCriterion("SUBMISSIONDATE =", value, "SUBMISSIONDATE");
            return (Criteria) this;
        }

        public Criteria andSUBMISSIONDATENotEqualTo(String value) {
            addCriterion("SUBMISSIONDATE <>", value, "SUBMISSIONDATE");
            return (Criteria) this;
        }

        public Criteria andSUBMISSIONDATEGreaterThan(String value) {
            addCriterion("SUBMISSIONDATE >", value, "SUBMISSIONDATE");
            return (Criteria) this;
        }

        public Criteria andSUBMISSIONDATEGreaterThanOrEqualTo(String value) {
            addCriterion("SUBMISSIONDATE >=", value, "SUBMISSIONDATE");
            return (Criteria) this;
        }

        public Criteria andSUBMISSIONDATELessThan(String value) {
            addCriterion("SUBMISSIONDATE <", value, "SUBMISSIONDATE");
            return (Criteria) this;
        }

        public Criteria andSUBMISSIONDATELessThanOrEqualTo(String value) {
            addCriterion("SUBMISSIONDATE <=", value, "SUBMISSIONDATE");
            return (Criteria) this;
        }

        public Criteria andSUBMISSIONDATELike(String value) {
            addCriterion("SUBMISSIONDATE like", value, "SUBMISSIONDATE");
            return (Criteria) this;
        }

        public Criteria andSUBMISSIONDATENotLike(String value) {
            addCriterion("SUBMISSIONDATE not like", value, "SUBMISSIONDATE");
            return (Criteria) this;
        }

        public Criteria andSUBMISSIONDATEIn(List<String> values) {
            addCriterion("SUBMISSIONDATE in", values, "SUBMISSIONDATE");
            return (Criteria) this;
        }

        public Criteria andSUBMISSIONDATENotIn(List<String> values) {
            addCriterion("SUBMISSIONDATE not in", values, "SUBMISSIONDATE");
            return (Criteria) this;
        }

        public Criteria andSUBMISSIONDATEBetween(String value1, String value2) {
            addCriterion("SUBMISSIONDATE between", value1, value2, "SUBMISSIONDATE");
            return (Criteria) this;
        }

        public Criteria andSUBMISSIONDATENotBetween(String value1, String value2) {
            addCriterion("SUBMISSIONDATE not between", value1, value2, "SUBMISSIONDATE");
            return (Criteria) this;
        }

        public Criteria andZSHYJIsNull() {
            addCriterion("ZSHYJ is null");
            return (Criteria) this;
        }

        public Criteria andZSHYJIsNotNull() {
            addCriterion("ZSHYJ is not null");
            return (Criteria) this;
        }

        public Criteria andZSHYJEqualTo(String value) {
            addCriterion("ZSHYJ =", value, "ZSHYJ");
            return (Criteria) this;
        }

        public Criteria andZSHYJNotEqualTo(String value) {
            addCriterion("ZSHYJ <>", value, "ZSHYJ");
            return (Criteria) this;
        }

        public Criteria andZSHYJGreaterThan(String value) {
            addCriterion("ZSHYJ >", value, "ZSHYJ");
            return (Criteria) this;
        }

        public Criteria andZSHYJGreaterThanOrEqualTo(String value) {
            addCriterion("ZSHYJ >=", value, "ZSHYJ");
            return (Criteria) this;
        }

        public Criteria andZSHYJLessThan(String value) {
            addCriterion("ZSHYJ <", value, "ZSHYJ");
            return (Criteria) this;
        }

        public Criteria andZSHYJLessThanOrEqualTo(String value) {
            addCriterion("ZSHYJ <=", value, "ZSHYJ");
            return (Criteria) this;
        }

        public Criteria andZSHYJLike(String value) {
            addCriterion("ZSHYJ like", value, "ZSHYJ");
            return (Criteria) this;
        }

        public Criteria andZSHYJNotLike(String value) {
            addCriterion("ZSHYJ not like", value, "ZSHYJ");
            return (Criteria) this;
        }

        public Criteria andZSHYJIn(List<String> values) {
            addCriterion("ZSHYJ in", values, "ZSHYJ");
            return (Criteria) this;
        }

        public Criteria andZSHYJNotIn(List<String> values) {
            addCriterion("ZSHYJ not in", values, "ZSHYJ");
            return (Criteria) this;
        }

        public Criteria andZSHYJBetween(String value1, String value2) {
            addCriterion("ZSHYJ between", value1, value2, "ZSHYJ");
            return (Criteria) this;
        }

        public Criteria andZSHYJNotBetween(String value1, String value2) {
            addCriterion("ZSHYJ not between", value1, value2, "ZSHYJ");
            return (Criteria) this;
        }

        public Criteria andZZSHRBPIsNull() {
            addCriterion("ZZSHRBP is null");
            return (Criteria) this;
        }

        public Criteria andZZSHRBPIsNotNull() {
            addCriterion("ZZSHRBP is not null");
            return (Criteria) this;
        }

        public Criteria andZZSHRBPEqualTo(String value) {
            addCriterion("ZZSHRBP =", value, "ZZSHRBP");
            return (Criteria) this;
        }

        public Criteria andZZSHRBPNotEqualTo(String value) {
            addCriterion("ZZSHRBP <>", value, "ZZSHRBP");
            return (Criteria) this;
        }

        public Criteria andZZSHRBPGreaterThan(String value) {
            addCriterion("ZZSHRBP >", value, "ZZSHRBP");
            return (Criteria) this;
        }

        public Criteria andZZSHRBPGreaterThanOrEqualTo(String value) {
            addCriterion("ZZSHRBP >=", value, "ZZSHRBP");
            return (Criteria) this;
        }

        public Criteria andZZSHRBPLessThan(String value) {
            addCriterion("ZZSHRBP <", value, "ZZSHRBP");
            return (Criteria) this;
        }

        public Criteria andZZSHRBPLessThanOrEqualTo(String value) {
            addCriterion("ZZSHRBP <=", value, "ZZSHRBP");
            return (Criteria) this;
        }

        public Criteria andZZSHRBPLike(String value) {
            addCriterion("ZZSHRBP like", value, "ZZSHRBP");
            return (Criteria) this;
        }

        public Criteria andZZSHRBPNotLike(String value) {
            addCriterion("ZZSHRBP not like", value, "ZZSHRBP");
            return (Criteria) this;
        }

        public Criteria andZZSHRBPIn(List<String> values) {
            addCriterion("ZZSHRBP in", values, "ZZSHRBP");
            return (Criteria) this;
        }

        public Criteria andZZSHRBPNotIn(List<String> values) {
            addCriterion("ZZSHRBP not in", values, "ZZSHRBP");
            return (Criteria) this;
        }

        public Criteria andZZSHRBPBetween(String value1, String value2) {
            addCriterion("ZZSHRBP between", value1, value2, "ZZSHRBP");
            return (Criteria) this;
        }

        public Criteria andZZSHRBPNotBetween(String value1, String value2) {
            addCriterion("ZZSHRBP not between", value1, value2, "ZZSHRBP");
            return (Criteria) this;
        }

        public Criteria andZZSHRXMIsNull() {
            addCriterion("ZZSHRXM is null");
            return (Criteria) this;
        }

        public Criteria andZZSHRXMIsNotNull() {
            addCriterion("ZZSHRXM is not null");
            return (Criteria) this;
        }

        public Criteria andZZSHRXMEqualTo(String value) {
            addCriterion("ZZSHRXM =", value, "ZZSHRXM");
            return (Criteria) this;
        }

        public Criteria andZZSHRXMNotEqualTo(String value) {
            addCriterion("ZZSHRXM <>", value, "ZZSHRXM");
            return (Criteria) this;
        }

        public Criteria andZZSHRXMGreaterThan(String value) {
            addCriterion("ZZSHRXM >", value, "ZZSHRXM");
            return (Criteria) this;
        }

        public Criteria andZZSHRXMGreaterThanOrEqualTo(String value) {
            addCriterion("ZZSHRXM >=", value, "ZZSHRXM");
            return (Criteria) this;
        }

        public Criteria andZZSHRXMLessThan(String value) {
            addCriterion("ZZSHRXM <", value, "ZZSHRXM");
            return (Criteria) this;
        }

        public Criteria andZZSHRXMLessThanOrEqualTo(String value) {
            addCriterion("ZZSHRXM <=", value, "ZZSHRXM");
            return (Criteria) this;
        }

        public Criteria andZZSHRXMLike(String value) {
            addCriterion("ZZSHRXM like", value, "ZZSHRXM");
            return (Criteria) this;
        }

        public Criteria andZZSHRXMNotLike(String value) {
            addCriterion("ZZSHRXM not like", value, "ZZSHRXM");
            return (Criteria) this;
        }

        public Criteria andZZSHRXMIn(List<String> values) {
            addCriterion("ZZSHRXM in", values, "ZZSHRXM");
            return (Criteria) this;
        }

        public Criteria andZZSHRXMNotIn(List<String> values) {
            addCriterion("ZZSHRXM not in", values, "ZZSHRXM");
            return (Criteria) this;
        }

        public Criteria andZZSHRXMBetween(String value1, String value2) {
            addCriterion("ZZSHRXM between", value1, value2, "ZZSHRXM");
            return (Criteria) this;
        }

        public Criteria andZZSHRXMNotBetween(String value1, String value2) {
            addCriterion("ZZSHRXM not between", value1, value2, "ZZSHRXM");
            return (Criteria) this;
        }

        public Criteria andZZSTATUSNEWIsNull() {
            addCriterion("ZZSTATUSNEW is null");
            return (Criteria) this;
        }

        public Criteria andZZSTATUSNEWIsNotNull() {
            addCriterion("ZZSTATUSNEW is not null");
            return (Criteria) this;
        }

        public Criteria andZZSTATUSNEWEqualTo(String value) {
            addCriterion("ZZSTATUSNEW =", value, "ZZSTATUSNEW");
            return (Criteria) this;
        }

        public Criteria andZZSTATUSNEWNotEqualTo(String value) {
            addCriterion("ZZSTATUSNEW <>", value, "ZZSTATUSNEW");
            return (Criteria) this;
        }

        public Criteria andZZSTATUSNEWGreaterThan(String value) {
            addCriterion("ZZSTATUSNEW >", value, "ZZSTATUSNEW");
            return (Criteria) this;
        }

        public Criteria andZZSTATUSNEWGreaterThanOrEqualTo(String value) {
            addCriterion("ZZSTATUSNEW >=", value, "ZZSTATUSNEW");
            return (Criteria) this;
        }

        public Criteria andZZSTATUSNEWLessThan(String value) {
            addCriterion("ZZSTATUSNEW <", value, "ZZSTATUSNEW");
            return (Criteria) this;
        }

        public Criteria andZZSTATUSNEWLessThanOrEqualTo(String value) {
            addCriterion("ZZSTATUSNEW <=", value, "ZZSTATUSNEW");
            return (Criteria) this;
        }

        public Criteria andZZSTATUSNEWLike(String value) {
            addCriterion("ZZSTATUSNEW like", value, "ZZSTATUSNEW");
            return (Criteria) this;
        }

        public Criteria andZZSTATUSNEWNotLike(String value) {
            addCriterion("ZZSTATUSNEW not like", value, "ZZSTATUSNEW");
            return (Criteria) this;
        }

        public Criteria andZZSTATUSNEWIn(List<String> values) {
            addCriterion("ZZSTATUSNEW in", values, "ZZSTATUSNEW");
            return (Criteria) this;
        }

        public Criteria andZZSTATUSNEWNotIn(List<String> values) {
            addCriterion("ZZSTATUSNEW not in", values, "ZZSTATUSNEW");
            return (Criteria) this;
        }

        public Criteria andZZSTATUSNEWBetween(String value1, String value2) {
            addCriterion("ZZSTATUSNEW between", value1, value2, "ZZSTATUSNEW");
            return (Criteria) this;
        }

        public Criteria andZZSTATUSNEWNotBetween(String value1, String value2) {
            addCriterion("ZZSTATUSNEW not between", value1, value2, "ZZSTATUSNEW");
            return (Criteria) this;
        }

        public Criteria andZZDATEIsNull() {
            addCriterion("ZZDATE is null");
            return (Criteria) this;
        }

        public Criteria andZZDATEIsNotNull() {
            addCriterion("ZZDATE is not null");
            return (Criteria) this;
        }

        public Criteria andZZDATEEqualTo(String value) {
            addCriterion("ZZDATE =", value, "ZZDATE");
            return (Criteria) this;
        }

        public Criteria andZZDATENotEqualTo(String value) {
            addCriterion("ZZDATE <>", value, "ZZDATE");
            return (Criteria) this;
        }

        public Criteria andZZDATEGreaterThan(String value) {
            addCriterion("ZZDATE >", value, "ZZDATE");
            return (Criteria) this;
        }

        public Criteria andZZDATEGreaterThanOrEqualTo(String value) {
            addCriterion("ZZDATE >=", value, "ZZDATE");
            return (Criteria) this;
        }

        public Criteria andZZDATELessThan(String value) {
            addCriterion("ZZDATE <", value, "ZZDATE");
            return (Criteria) this;
        }

        public Criteria andZZDATELessThanOrEqualTo(String value) {
            addCriterion("ZZDATE <=", value, "ZZDATE");
            return (Criteria) this;
        }

        public Criteria andZZDATELike(String value) {
            addCriterion("ZZDATE like", value, "ZZDATE");
            return (Criteria) this;
        }

        public Criteria andZZDATENotLike(String value) {
            addCriterion("ZZDATE not like", value, "ZZDATE");
            return (Criteria) this;
        }

        public Criteria andZZDATEIn(List<String> values) {
            addCriterion("ZZDATE in", values, "ZZDATE");
            return (Criteria) this;
        }

        public Criteria andZZDATENotIn(List<String> values) {
            addCriterion("ZZDATE not in", values, "ZZDATE");
            return (Criteria) this;
        }

        public Criteria andZZDATEBetween(String value1, String value2) {
            addCriterion("ZZDATE between", value1, value2, "ZZDATE");
            return (Criteria) this;
        }

        public Criteria andZZDATENotBetween(String value1, String value2) {
            addCriterion("ZZDATE not between", value1, value2, "ZZDATE");
            return (Criteria) this;
        }

        public Criteria andZZTIMEIsNull() {
            addCriterion("ZZTIME is null");
            return (Criteria) this;
        }

        public Criteria andZZTIMEIsNotNull() {
            addCriterion("ZZTIME is not null");
            return (Criteria) this;
        }

        public Criteria andZZTIMEEqualTo(String value) {
            addCriterion("ZZTIME =", value, "ZZTIME");
            return (Criteria) this;
        }

        public Criteria andZZTIMENotEqualTo(String value) {
            addCriterion("ZZTIME <>", value, "ZZTIME");
            return (Criteria) this;
        }

        public Criteria andZZTIMEGreaterThan(String value) {
            addCriterion("ZZTIME >", value, "ZZTIME");
            return (Criteria) this;
        }

        public Criteria andZZTIMEGreaterThanOrEqualTo(String value) {
            addCriterion("ZZTIME >=", value, "ZZTIME");
            return (Criteria) this;
        }

        public Criteria andZZTIMELessThan(String value) {
            addCriterion("ZZTIME <", value, "ZZTIME");
            return (Criteria) this;
        }

        public Criteria andZZTIMELessThanOrEqualTo(String value) {
            addCriterion("ZZTIME <=", value, "ZZTIME");
            return (Criteria) this;
        }

        public Criteria andZZTIMELike(String value) {
            addCriterion("ZZTIME like", value, "ZZTIME");
            return (Criteria) this;
        }

        public Criteria andZZTIMENotLike(String value) {
            addCriterion("ZZTIME not like", value, "ZZTIME");
            return (Criteria) this;
        }

        public Criteria andZZTIMEIn(List<String> values) {
            addCriterion("ZZTIME in", values, "ZZTIME");
            return (Criteria) this;
        }

        public Criteria andZZTIMENotIn(List<String> values) {
            addCriterion("ZZTIME not in", values, "ZZTIME");
            return (Criteria) this;
        }

        public Criteria andZZTIMEBetween(String value1, String value2) {
            addCriterion("ZZTIME between", value1, value2, "ZZTIME");
            return (Criteria) this;
        }

        public Criteria andZZTIMENotBetween(String value1, String value2) {
            addCriterion("ZZTIME not between", value1, value2, "ZZTIME");
            return (Criteria) this;
        }

        public Criteria andPROPOSERIDIsNull() {
            addCriterion("PROPOSERID is null");
            return (Criteria) this;
        }

        public Criteria andPROPOSERIDIsNotNull() {
            addCriterion("PROPOSERID is not null");
            return (Criteria) this;
        }

        public Criteria andPROPOSERIDEqualTo(String value) {
            addCriterion("PROPOSERID =", value, "PROPOSERID");
            return (Criteria) this;
        }

        public Criteria andPROPOSERIDNotEqualTo(String value) {
            addCriterion("PROPOSERID <>", value, "PROPOSERID");
            return (Criteria) this;
        }

        public Criteria andPROPOSERIDGreaterThan(String value) {
            addCriterion("PROPOSERID >", value, "PROPOSERID");
            return (Criteria) this;
        }

        public Criteria andPROPOSERIDGreaterThanOrEqualTo(String value) {
            addCriterion("PROPOSERID >=", value, "PROPOSERID");
            return (Criteria) this;
        }

        public Criteria andPROPOSERIDLessThan(String value) {
            addCriterion("PROPOSERID <", value, "PROPOSERID");
            return (Criteria) this;
        }

        public Criteria andPROPOSERIDLessThanOrEqualTo(String value) {
            addCriterion("PROPOSERID <=", value, "PROPOSERID");
            return (Criteria) this;
        }

        public Criteria andPROPOSERIDLike(String value) {
            addCriterion("PROPOSERID like", value, "PROPOSERID");
            return (Criteria) this;
        }

        public Criteria andPROPOSERIDNotLike(String value) {
            addCriterion("PROPOSERID not like", value, "PROPOSERID");
            return (Criteria) this;
        }

        public Criteria andPROPOSERIDIn(List<String> values) {
            addCriterion("PROPOSERID in", values, "PROPOSERID");
            return (Criteria) this;
        }

        public Criteria andPROPOSERIDNotIn(List<String> values) {
            addCriterion("PROPOSERID not in", values, "PROPOSERID");
            return (Criteria) this;
        }

        public Criteria andPROPOSERIDBetween(String value1, String value2) {
            addCriterion("PROPOSERID between", value1, value2, "PROPOSERID");
            return (Criteria) this;
        }

        public Criteria andPROPOSERIDNotBetween(String value1, String value2) {
            addCriterion("PROPOSERID not between", value1, value2, "PROPOSERID");
            return (Criteria) this;
        }

        public Criteria andISSENDIsNull() {
            addCriterion("ISSEND is null");
            return (Criteria) this;
        }

        public Criteria andISSENDIsNotNull() {
            addCriterion("ISSEND is not null");
            return (Criteria) this;
        }

        public Criteria andISSENDEqualTo(String value) {
            addCriterion("ISSEND =", value, "ISSEND");
            return (Criteria) this;
        }

        public Criteria andISSENDNotEqualTo(String value) {
            addCriterion("ISSEND <>", value, "ISSEND");
            return (Criteria) this;
        }

        public Criteria andISSENDGreaterThan(String value) {
            addCriterion("ISSEND >", value, "ISSEND");
            return (Criteria) this;
        }

        public Criteria andISSENDGreaterThanOrEqualTo(String value) {
            addCriterion("ISSEND >=", value, "ISSEND");
            return (Criteria) this;
        }

        public Criteria andISSENDLessThan(String value) {
            addCriterion("ISSEND <", value, "ISSEND");
            return (Criteria) this;
        }

        public Criteria andISSENDLessThanOrEqualTo(String value) {
            addCriterion("ISSEND <=", value, "ISSEND");
            return (Criteria) this;
        }

        public Criteria andISSENDLike(String value) {
            addCriterion("ISSEND like", value, "ISSEND");
            return (Criteria) this;
        }

        public Criteria andISSENDNotLike(String value) {
            addCriterion("ISSEND not like", value, "ISSEND");
            return (Criteria) this;
        }

        public Criteria andISSENDIn(List<String> values) {
            addCriterion("ISSEND in", values, "ISSEND");
            return (Criteria) this;
        }

        public Criteria andISSENDNotIn(List<String> values) {
            addCriterion("ISSEND not in", values, "ISSEND");
            return (Criteria) this;
        }

        public Criteria andISSENDBetween(String value1, String value2) {
            addCriterion("ISSEND between", value1, value2, "ISSEND");
            return (Criteria) this;
        }

        public Criteria andISSENDNotBetween(String value1, String value2) {
            addCriterion("ISSEND not between", value1, value2, "ISSEND");
            return (Criteria) this;
        }

        public Criteria andRETURNSTATEIsNull() {
            addCriterion("RETURNSTATE is null");
            return (Criteria) this;
        }

        public Criteria andRETURNSTATEIsNotNull() {
            addCriterion("RETURNSTATE is not null");
            return (Criteria) this;
        }

        public Criteria andRETURNSTATEEqualTo(String value) {
            addCriterion("RETURNSTATE =", value, "RETURNSTATE");
            return (Criteria) this;
        }

        public Criteria andRETURNSTATENotEqualTo(String value) {
            addCriterion("RETURNSTATE <>", value, "RETURNSTATE");
            return (Criteria) this;
        }

        public Criteria andRETURNSTATEGreaterThan(String value) {
            addCriterion("RETURNSTATE >", value, "RETURNSTATE");
            return (Criteria) this;
        }

        public Criteria andRETURNSTATEGreaterThanOrEqualTo(String value) {
            addCriterion("RETURNSTATE >=", value, "RETURNSTATE");
            return (Criteria) this;
        }

        public Criteria andRETURNSTATELessThan(String value) {
            addCriterion("RETURNSTATE <", value, "RETURNSTATE");
            return (Criteria) this;
        }

        public Criteria andRETURNSTATELessThanOrEqualTo(String value) {
            addCriterion("RETURNSTATE <=", value, "RETURNSTATE");
            return (Criteria) this;
        }

        public Criteria andRETURNSTATELike(String value) {
            addCriterion("RETURNSTATE like", value, "RETURNSTATE");
            return (Criteria) this;
        }

        public Criteria andRETURNSTATENotLike(String value) {
            addCriterion("RETURNSTATE not like", value, "RETURNSTATE");
            return (Criteria) this;
        }

        public Criteria andRETURNSTATEIn(List<String> values) {
            addCriterion("RETURNSTATE in", values, "RETURNSTATE");
            return (Criteria) this;
        }

        public Criteria andRETURNSTATENotIn(List<String> values) {
            addCriterion("RETURNSTATE not in", values, "RETURNSTATE");
            return (Criteria) this;
        }

        public Criteria andRETURNSTATEBetween(String value1, String value2) {
            addCriterion("RETURNSTATE between", value1, value2, "RETURNSTATE");
            return (Criteria) this;
        }

        public Criteria andRETURNSTATENotBetween(String value1, String value2) {
            addCriterion("RETURNSTATE not between", value1, value2, "RETURNSTATE");
            return (Criteria) this;
        }

        public Criteria andRETURNMESIsNull() {
            addCriterion("RETURNMES is null");
            return (Criteria) this;
        }

        public Criteria andRETURNMESIsNotNull() {
            addCriterion("RETURNMES is not null");
            return (Criteria) this;
        }

        public Criteria andRETURNMESEqualTo(String value) {
            addCriterion("RETURNMES =", value, "RETURNMES");
            return (Criteria) this;
        }

        public Criteria andRETURNMESNotEqualTo(String value) {
            addCriterion("RETURNMES <>", value, "RETURNMES");
            return (Criteria) this;
        }

        public Criteria andRETURNMESGreaterThan(String value) {
            addCriterion("RETURNMES >", value, "RETURNMES");
            return (Criteria) this;
        }

        public Criteria andRETURNMESGreaterThanOrEqualTo(String value) {
            addCriterion("RETURNMES >=", value, "RETURNMES");
            return (Criteria) this;
        }

        public Criteria andRETURNMESLessThan(String value) {
            addCriterion("RETURNMES <", value, "RETURNMES");
            return (Criteria) this;
        }

        public Criteria andRETURNMESLessThanOrEqualTo(String value) {
            addCriterion("RETURNMES <=", value, "RETURNMES");
            return (Criteria) this;
        }

        public Criteria andRETURNMESLike(String value) {
            addCriterion("RETURNMES like", value, "RETURNMES");
            return (Criteria) this;
        }

        public Criteria andRETURNMESNotLike(String value) {
            addCriterion("RETURNMES not like", value, "RETURNMES");
            return (Criteria) this;
        }

        public Criteria andRETURNMESIn(List<String> values) {
            addCriterion("RETURNMES in", values, "RETURNMES");
            return (Criteria) this;
        }

        public Criteria andRETURNMESNotIn(List<String> values) {
            addCriterion("RETURNMES not in", values, "RETURNMES");
            return (Criteria) this;
        }

        public Criteria andRETURNMESBetween(String value1, String value2) {
            addCriterion("RETURNMES between", value1, value2, "RETURNMES");
            return (Criteria) this;
        }

        public Criteria andRETURNMESNotBetween(String value1, String value2) {
            addCriterion("RETURNMES not between", value1, value2, "RETURNMES");
            return (Criteria) this;
        }

        public Criteria andZZBELNRIsNull() {
            addCriterion("ZZBELNR is null");
            return (Criteria) this;
        }

        public Criteria andZZBELNRIsNotNull() {
            addCriterion("ZZBELNR is not null");
            return (Criteria) this;
        }

        public Criteria andZZBELNREqualTo(String value) {
            addCriterion("ZZBELNR =", value, "ZZBELNR");
            return (Criteria) this;
        }

        public Criteria andZZBELNRNotEqualTo(String value) {
            addCriterion("ZZBELNR <>", value, "ZZBELNR");
            return (Criteria) this;
        }

        public Criteria andZZBELNRGreaterThan(String value) {
            addCriterion("ZZBELNR >", value, "ZZBELNR");
            return (Criteria) this;
        }

        public Criteria andZZBELNRGreaterThanOrEqualTo(String value) {
            addCriterion("ZZBELNR >=", value, "ZZBELNR");
            return (Criteria) this;
        }

        public Criteria andZZBELNRLessThan(String value) {
            addCriterion("ZZBELNR <", value, "ZZBELNR");
            return (Criteria) this;
        }

        public Criteria andZZBELNRLessThanOrEqualTo(String value) {
            addCriterion("ZZBELNR <=", value, "ZZBELNR");
            return (Criteria) this;
        }

        public Criteria andZZBELNRLike(String value) {
            addCriterion("ZZBELNR like", value, "ZZBELNR");
            return (Criteria) this;
        }

        public Criteria andZZBELNRNotLike(String value) {
            addCriterion("ZZBELNR not like", value, "ZZBELNR");
            return (Criteria) this;
        }

        public Criteria andZZBELNRIn(List<String> values) {
            addCriterion("ZZBELNR in", values, "ZZBELNR");
            return (Criteria) this;
        }

        public Criteria andZZBELNRNotIn(List<String> values) {
            addCriterion("ZZBELNR not in", values, "ZZBELNR");
            return (Criteria) this;
        }

        public Criteria andZZBELNRBetween(String value1, String value2) {
            addCriterion("ZZBELNR between", value1, value2, "ZZBELNR");
            return (Criteria) this;
        }

        public Criteria andZZBELNRNotBetween(String value1, String value2) {
            addCriterion("ZZBELNR not between", value1, value2, "ZZBELNR");
            return (Criteria) this;
        }

        public Criteria andISSENDTOSAPIsNull() {
            addCriterion("ISSENDTOSAP is null");
            return (Criteria) this;
        }

        public Criteria andISSENDTOSAPIsNotNull() {
            addCriterion("ISSENDTOSAP is not null");
            return (Criteria) this;
        }

        public Criteria andISSENDTOSAPEqualTo(String value) {
            addCriterion("ISSENDTOSAP =", value, "ISSENDTOSAP");
            return (Criteria) this;
        }

        public Criteria andISSENDTOSAPNotEqualTo(String value) {
            addCriterion("ISSENDTOSAP <>", value, "ISSENDTOSAP");
            return (Criteria) this;
        }

        public Criteria andISSENDTOSAPGreaterThan(String value) {
            addCriterion("ISSENDTOSAP >", value, "ISSENDTOSAP");
            return (Criteria) this;
        }

        public Criteria andISSENDTOSAPGreaterThanOrEqualTo(String value) {
            addCriterion("ISSENDTOSAP >=", value, "ISSENDTOSAP");
            return (Criteria) this;
        }

        public Criteria andISSENDTOSAPLessThan(String value) {
            addCriterion("ISSENDTOSAP <", value, "ISSENDTOSAP");
            return (Criteria) this;
        }

        public Criteria andISSENDTOSAPLessThanOrEqualTo(String value) {
            addCriterion("ISSENDTOSAP <=", value, "ISSENDTOSAP");
            return (Criteria) this;
        }

        public Criteria andISSENDTOSAPLike(String value) {
            addCriterion("ISSENDTOSAP like", value, "ISSENDTOSAP");
            return (Criteria) this;
        }

        public Criteria andISSENDTOSAPNotLike(String value) {
            addCriterion("ISSENDTOSAP not like", value, "ISSENDTOSAP");
            return (Criteria) this;
        }

        public Criteria andISSENDTOSAPIn(List<String> values) {
            addCriterion("ISSENDTOSAP in", values, "ISSENDTOSAP");
            return (Criteria) this;
        }

        public Criteria andISSENDTOSAPNotIn(List<String> values) {
            addCriterion("ISSENDTOSAP not in", values, "ISSENDTOSAP");
            return (Criteria) this;
        }

        public Criteria andISSENDTOSAPBetween(String value1, String value2) {
            addCriterion("ISSENDTOSAP between", value1, value2, "ISSENDTOSAP");
            return (Criteria) this;
        }

        public Criteria andISSENDTOSAPNotBetween(String value1, String value2) {
            addCriterion("ISSENDTOSAP not between", value1, value2, "ISSENDTOSAP");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_COMMON_TASK
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_COMMON_TASK
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}