package com.zhy.people.beans;

public class CommonTask {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COMMON_TASK.FLOWID
     *
     * @mbg.generated
     */
    private String FLOWID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COMMON_TASK.TASKID
     *
     * @mbg.generated
     */
    private String TASKID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COMMON_TASK.PROCESSINSTANCEID
     *
     * @mbg.generated
     */
    private String PROCESSINSTANCEID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COMMON_TASK.TYPEID
     *
     * @mbg.generated
     */
    private String TYPEID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COMMON_TASK.FLOWNAME
     *
     * @mbg.generated
     */
    private String FLOWNAME;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COMMON_TASK.PROPOSER
     *
     * @mbg.generated
     */
    private String PROPOSER;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COMMON_TASK.TASKNAME
     *
     * @mbg.generated
     */
    private String TASKNAME;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COMMON_TASK.STATE
     *
     * @mbg.generated
     */
    private String STATE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COMMON_TASK.SUBMISSIONDATE
     *
     * @mbg.generated
     */
    private String SUBMISSIONDATE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COMMON_TASK.ZSHYJ
     *
     * @mbg.generated
     */
    private String ZSHYJ;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COMMON_TASK.ZZSHRBP
     *
     * @mbg.generated
     */
    private String ZZSHRBP;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COMMON_TASK.ZZSHRXM
     *
     * @mbg.generated
     */
    private String ZZSHRXM;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COMMON_TASK.ZZSTATUSNEW
     *
     * @mbg.generated
     */
    private String ZZSTATUSNEW;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COMMON_TASK.ZZDATE
     *
     * @mbg.generated
     */
    private String ZZDATE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COMMON_TASK.ZZTIME
     *
     * @mbg.generated
     */
    private String ZZTIME;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COMMON_TASK.PROPOSERID
     *
     * @mbg.generated
     */
    private String PROPOSERID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COMMON_TASK.ISSEND
     *
     * @mbg.generated
     */
    private String ISSEND;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COMMON_TASK.RETURNSTATE
     *
     * @mbg.generated
     */
    private String RETURNSTATE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COMMON_TASK.RETURNMES
     *
     * @mbg.generated
     */
    private String RETURNMES;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COMMON_TASK.ZZBELNR
     *
     * @mbg.generated
     */
    private String ZZBELNR;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COMMON_TASK.ISSENDTOSAP
     *
     * @mbg.generated
     */
    private String ISSENDTOSAP;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COMMON_TASK.FLOWID
     *
     * @return the value of T_COMMON_TASK.FLOWID
     *
     * @mbg.generated
     */
    public String getFLOWID() {
        return FLOWID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COMMON_TASK.FLOWID
     *
     * @param FLOWID the value for T_COMMON_TASK.FLOWID
     *
     * @mbg.generated
     */
    public void setFLOWID(String FLOWID) {
        this.FLOWID = FLOWID == null ? null : FLOWID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COMMON_TASK.TASKID
     *
     * @return the value of T_COMMON_TASK.TASKID
     *
     * @mbg.generated
     */
    public String getTASKID() {
        return TASKID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COMMON_TASK.TASKID
     *
     * @param TASKID the value for T_COMMON_TASK.TASKID
     *
     * @mbg.generated
     */
    public void setTASKID(String TASKID) {
        this.TASKID = TASKID == null ? null : TASKID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COMMON_TASK.PROCESSINSTANCEID
     *
     * @return the value of T_COMMON_TASK.PROCESSINSTANCEID
     *
     * @mbg.generated
     */
    public String getPROCESSINSTANCEID() {
        return PROCESSINSTANCEID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COMMON_TASK.PROCESSINSTANCEID
     *
     * @param PROCESSINSTANCEID the value for T_COMMON_TASK.PROCESSINSTANCEID
     *
     * @mbg.generated
     */
    public void setPROCESSINSTANCEID(String PROCESSINSTANCEID) {
        this.PROCESSINSTANCEID = PROCESSINSTANCEID == null ? null : PROCESSINSTANCEID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COMMON_TASK.TYPEID
     *
     * @return the value of T_COMMON_TASK.TYPEID
     *
     * @mbg.generated
     */
    public String getTYPEID() {
        return TYPEID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COMMON_TASK.TYPEID
     *
     * @param TYPEID the value for T_COMMON_TASK.TYPEID
     *
     * @mbg.generated
     */
    public void setTYPEID(String TYPEID) {
        this.TYPEID = TYPEID == null ? null : TYPEID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COMMON_TASK.FLOWNAME
     *
     * @return the value of T_COMMON_TASK.FLOWNAME
     *
     * @mbg.generated
     */
    public String getFLOWNAME() {
        return FLOWNAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COMMON_TASK.FLOWNAME
     *
     * @param FLOWNAME the value for T_COMMON_TASK.FLOWNAME
     *
     * @mbg.generated
     */
    public void setFLOWNAME(String FLOWNAME) {
        this.FLOWNAME = FLOWNAME == null ? null : FLOWNAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COMMON_TASK.PROPOSER
     *
     * @return the value of T_COMMON_TASK.PROPOSER
     *
     * @mbg.generated
     */
    public String getPROPOSER() {
        return PROPOSER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COMMON_TASK.PROPOSER
     *
     * @param PROPOSER the value for T_COMMON_TASK.PROPOSER
     *
     * @mbg.generated
     */
    public void setPROPOSER(String PROPOSER) {
        this.PROPOSER = PROPOSER == null ? null : PROPOSER.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COMMON_TASK.TASKNAME
     *
     * @return the value of T_COMMON_TASK.TASKNAME
     *
     * @mbg.generated
     */
    public String getTASKNAME() {
        return TASKNAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COMMON_TASK.TASKNAME
     *
     * @param TASKNAME the value for T_COMMON_TASK.TASKNAME
     *
     * @mbg.generated
     */
    public void setTASKNAME(String TASKNAME) {
        this.TASKNAME = TASKNAME == null ? null : TASKNAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COMMON_TASK.STATE
     *
     * @return the value of T_COMMON_TASK.STATE
     *
     * @mbg.generated
     */
    public String getSTATE() {
        return STATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COMMON_TASK.STATE
     *
     * @param STATE the value for T_COMMON_TASK.STATE
     *
     * @mbg.generated
     */
    public void setSTATE(String STATE) {
        this.STATE = STATE == null ? null : STATE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COMMON_TASK.SUBMISSIONDATE
     *
     * @return the value of T_COMMON_TASK.SUBMISSIONDATE
     *
     * @mbg.generated
     */
    public String getSUBMISSIONDATE() {
        return SUBMISSIONDATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COMMON_TASK.SUBMISSIONDATE
     *
     * @param SUBMISSIONDATE the value for T_COMMON_TASK.SUBMISSIONDATE
     *
     * @mbg.generated
     */
    public void setSUBMISSIONDATE(String SUBMISSIONDATE) {
        this.SUBMISSIONDATE = SUBMISSIONDATE == null ? null : SUBMISSIONDATE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COMMON_TASK.ZSHYJ
     *
     * @return the value of T_COMMON_TASK.ZSHYJ
     *
     * @mbg.generated
     */
    public String getZSHYJ() {
        return ZSHYJ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COMMON_TASK.ZSHYJ
     *
     * @param ZSHYJ the value for T_COMMON_TASK.ZSHYJ
     *
     * @mbg.generated
     */
    public void setZSHYJ(String ZSHYJ) {
        this.ZSHYJ = ZSHYJ == null ? null : ZSHYJ.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COMMON_TASK.ZZSHRBP
     *
     * @return the value of T_COMMON_TASK.ZZSHRBP
     *
     * @mbg.generated
     */
    public String getZZSHRBP() {
        return ZZSHRBP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COMMON_TASK.ZZSHRBP
     *
     * @param ZZSHRBP the value for T_COMMON_TASK.ZZSHRBP
     *
     * @mbg.generated
     */
    public void setZZSHRBP(String ZZSHRBP) {
        this.ZZSHRBP = ZZSHRBP == null ? null : ZZSHRBP.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COMMON_TASK.ZZSHRXM
     *
     * @return the value of T_COMMON_TASK.ZZSHRXM
     *
     * @mbg.generated
     */
    public String getZZSHRXM() {
        return ZZSHRXM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COMMON_TASK.ZZSHRXM
     *
     * @param ZZSHRXM the value for T_COMMON_TASK.ZZSHRXM
     *
     * @mbg.generated
     */
    public void setZZSHRXM(String ZZSHRXM) {
        this.ZZSHRXM = ZZSHRXM == null ? null : ZZSHRXM.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COMMON_TASK.ZZSTATUSNEW
     *
     * @return the value of T_COMMON_TASK.ZZSTATUSNEW
     *
     * @mbg.generated
     */
    public String getZZSTATUSNEW() {
        return ZZSTATUSNEW;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COMMON_TASK.ZZSTATUSNEW
     *
     * @param ZZSTATUSNEW the value for T_COMMON_TASK.ZZSTATUSNEW
     *
     * @mbg.generated
     */
    public void setZZSTATUSNEW(String ZZSTATUSNEW) {
        this.ZZSTATUSNEW = ZZSTATUSNEW == null ? null : ZZSTATUSNEW.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COMMON_TASK.ZZDATE
     *
     * @return the value of T_COMMON_TASK.ZZDATE
     *
     * @mbg.generated
     */
    public String getZZDATE() {
        return ZZDATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COMMON_TASK.ZZDATE
     *
     * @param ZZDATE the value for T_COMMON_TASK.ZZDATE
     *
     * @mbg.generated
     */
    public void setZZDATE(String ZZDATE) {
        this.ZZDATE = ZZDATE == null ? null : ZZDATE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COMMON_TASK.ZZTIME
     *
     * @return the value of T_COMMON_TASK.ZZTIME
     *
     * @mbg.generated
     */
    public String getZZTIME() {
        return ZZTIME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COMMON_TASK.ZZTIME
     *
     * @param ZZTIME the value for T_COMMON_TASK.ZZTIME
     *
     * @mbg.generated
     */
    public void setZZTIME(String ZZTIME) {
        this.ZZTIME = ZZTIME == null ? null : ZZTIME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COMMON_TASK.PROPOSERID
     *
     * @return the value of T_COMMON_TASK.PROPOSERID
     *
     * @mbg.generated
     */
    public String getPROPOSERID() {
        return PROPOSERID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COMMON_TASK.PROPOSERID
     *
     * @param PROPOSERID the value for T_COMMON_TASK.PROPOSERID
     *
     * @mbg.generated
     */
    public void setPROPOSERID(String PROPOSERID) {
        this.PROPOSERID = PROPOSERID == null ? null : PROPOSERID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COMMON_TASK.ISSEND
     *
     * @return the value of T_COMMON_TASK.ISSEND
     *
     * @mbg.generated
     */
    public String getISSEND() {
        return ISSEND;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COMMON_TASK.ISSEND
     *
     * @param ISSEND the value for T_COMMON_TASK.ISSEND
     *
     * @mbg.generated
     */
    public void setISSEND(String ISSEND) {
        this.ISSEND = ISSEND == null ? null : ISSEND.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COMMON_TASK.RETURNSTATE
     *
     * @return the value of T_COMMON_TASK.RETURNSTATE
     *
     * @mbg.generated
     */
    public String getRETURNSTATE() {
        return RETURNSTATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COMMON_TASK.RETURNSTATE
     *
     * @param RETURNSTATE the value for T_COMMON_TASK.RETURNSTATE
     *
     * @mbg.generated
     */
    public void setRETURNSTATE(String RETURNSTATE) {
        this.RETURNSTATE = RETURNSTATE == null ? null : RETURNSTATE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COMMON_TASK.RETURNMES
     *
     * @return the value of T_COMMON_TASK.RETURNMES
     *
     * @mbg.generated
     */
    public String getRETURNMES() {
        return RETURNMES;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COMMON_TASK.RETURNMES
     *
     * @param RETURNMES the value for T_COMMON_TASK.RETURNMES
     *
     * @mbg.generated
     */
    public void setRETURNMES(String RETURNMES) {
        this.RETURNMES = RETURNMES == null ? null : RETURNMES.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COMMON_TASK.ZZBELNR
     *
     * @return the value of T_COMMON_TASK.ZZBELNR
     *
     * @mbg.generated
     */
    public String getZZBELNR() {
        return ZZBELNR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COMMON_TASK.ZZBELNR
     *
     * @param ZZBELNR the value for T_COMMON_TASK.ZZBELNR
     *
     * @mbg.generated
     */
    public void setZZBELNR(String ZZBELNR) {
        this.ZZBELNR = ZZBELNR == null ? null : ZZBELNR.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COMMON_TASK.ISSENDTOSAP
     *
     * @return the value of T_COMMON_TASK.ISSENDTOSAP
     *
     * @mbg.generated
     */
    public String getISSENDTOSAP() {
        return ISSENDTOSAP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COMMON_TASK.ISSENDTOSAP
     *
     * @param ISSENDTOSAP the value for T_COMMON_TASK.ISSENDTOSAP
     *
     * @mbg.generated
     */
    public void setISSENDTOSAP(String ISSENDTOSAP) {
        this.ISSENDTOSAP = ISSENDTOSAP == null ? null : ISSENDTOSAP.trim();
    }
}