package com.zhy.people.mappers;

import com.zhy.people.beans.B;
import com.zhy.people.beans.BExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b
     *
     * @mbg.generated
     */
    long countByExample(BExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b
     *
     * @mbg.generated
     */
    int deleteByExample(BExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b
     *
     * @mbg.generated
     */
    int insert(B record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b
     *
     * @mbg.generated
     */
    int insertSelective(B record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b
     *
     * @mbg.generated
     */
    List<B> selectByExample(BExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b
     *
     * @mbg.generated
     */
    B selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") B record, @Param("example") BExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") B record, @Param("example") BExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(B record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(B record);
}